spring:
  redis:
    database: 0
    lettuce:
      pool:
        max-active: 10
        min-idle: 10
        max-idle: 100
        max-wait: 10000
      shutdown-timeout: 1000ms
    password: FuckHao123
    host: 154.8.141.197
    port: 6378
server:
  port: 8080